[project]
name = "khoroos"
version = "0.1.0"
description = "An open toolkit for poultry welfare monitoring."
authors = [
    { name = "Ahmad Amirivojdan", email = "amirivojdan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[build-system]
requires = ["uv_build>=0.9.11,<0.10.0"]
build-backend = "uv_build"
